container:
  image: gradle:jdk8
  cpu: 4
  memory: 12G

task:
  auto_cancellation: $CIRRUS_PR != ''
  setup_workspace_script: chmod +x ./gradlew
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      cat gradle/wrapper/gradle-wrapper.properties
    populate_script: ./gradlew setupDevWorkspace
  matrix:
  - name: Build Job
    script: |
      rm -rf $CIRRUS_WORKING_DIR/src/main/resources/build.txt
      echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
      ./gradlew build
    jar_artifacts:
      path: ./build/libs/**
  - name: Test Job
    script: |
      ./gradlew test
  always:
    cleanup_before_cache_script: |
      rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      rm -rf ~/.gradle/caches/4.0.2/
      find ~/.gradle/caches/ -name "*.lock" -type f -delete

task:
  name: Code Coverage Job
  auto_cancellation: false
  container:
    image: endeveit/docker-jq:latest
  env:
    CODACY_PROJECT_TOKEN: ENCRYPTED[c3b8a1a2c14d5a6efcd3eecaf4f12e6bd2f3de2ad39650e7be37ee0a3ba6e71d8ba8133023bba20340e01b1f004db629]
  install_script: |
    curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
    chmod +x codacy-coverage-reporter
  script: |
    export CI_COMMIT=${CIRRUS_CHANGE_IN_REPO}
    ./codacy-coverage-reporter report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
