task:
  auto_cancellation: true
  container:
    image: gradle:4.10-jdk 
    cpu: 4
    memory: 12G
  setup_workspace_script: |
    rm -rf $CIRRUS_WORKING_DIR/src/main/resources/build.txt
    echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      cat gradle/wrapper/gradle-wrapper.properties
    populate_script: gradle setupDevWorkspace
  matrix:
  - name: Build Job
    script: gradle build
    jar_artifacts:
      path: ./build/libs/**
  - name: Test Job
    script: gradle test
  always:
    cleanup_before_cache_script: |
      rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      find ~/.gradle/caches/ -name "*.lock" -type f -delete
