task:
  auto_cancellation: $CIRRUS_BRANCH != 'master' && $CIRRUS_TAG != ''
  container:
    image: gradle:4.10.3-jdk8
    cpu: 8
    memory: 16G
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: cat build.gradle
    populate_script: gradle setupCiWorkspace --build-cache --parallel -Dorg.gradle.jvmargs=-Xmx14336M
  script: gradle build sha512 --parallel -Dorg.gradle.jvmargs=-Xmx14336M
  jar_artifacts:
    path: ./build/libs/*.jar
    type: application/java-archive
  checksum_artifacts:
    path: ./build/libs/*.sha512
    type: text/plain
  matrix:
    - name: Cirrus CI
    - name: deploy
      env:
        CR_DEPLOY_TOKEN: ENCRYPTED[1a2ed7d9ed2efa1ee67511efb5d40a10ae7764ba1007d5932f9dd6fba02be03f8fff6cbcf2ffbc62c43b8dc4f09f9ec8]
      deploy_script: |
        chmod +x .github/cloudrepo_deploy.sh
        bash .github/cloudrepo_deploy.sh
  always:
    cleanup_before_cache_script: |
      rm -rf ~/.gradle/caches/$GRADLE_VERSION/ ~/.gradle/caches/transforms-1 ~/.gradle/caches/journal-1 ~/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar ~/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
      find ~/.gradle/caches/ -name "*.lock" -type f -delete
