task:
  auto_cancellation: $CIRRUS_BRANCH != 'master' && $CIRRUS_TAG != ''
  container:
    image: gradle:4.10.3-jdk8
    cpu: 3
    memory: 10G
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: cat build.gradle
    populate_script: gradle setupCiWorkspace --build-cache -Dorg.gradle.jvmargs=-Xmx11264M
  script: gradle build -Dorg.gradle.jvmargs=-Xmx11264M
  jar_artifacts:
    path: ./build/libs/*.jar
    type: application/java-archive
  name: Cirrus CI
  cleanup_before_cache_script: |
    rm -rf ~/.gradle/caches/$GRADLE_VERSION/ ~/.gradle/caches/transforms-1 ~/.gradle/caches/journal-1 ~/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar ~/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
    find ~/.gradle/caches/ -name "*.lock" -type f -delete
